stages:
    - test
    - pages
    - package

cache:
    paths:
        - public/


########
# Test #
########

test:
    image: python
    stage: test
    script:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
        - pip install -U setuptools
        - python setup.py test
        - mv htmlcov public/


#####################
# Build Sphinx Docs #
#####################
# use docker image with latex preinstalled

pages:
    image: python
    stage: pages
    script:
        - apt-get --yes update && apt-get --yes install git
        - pip install -r requirements.txt
        - pip install -U setuptools
        - python setup.py docs
        - mv docs/_build/html public/
    tags:
        - docker
    artifacts:
        paths:
        - public
