stages:
    - test
    - pages
    - package


before_script:
    - bash setup.sh

########
# Test #
########

test_x86:
    image: python
    stage: test
    script:
        - pip install -r test-requirements.txt
        - python setup.py test
    tags:
        - docker
        - x86

test_armv7l:
    stage: test
    script:
        - pip3 install -r test-requirements.txt
        - python3 setup.py test
    tags:
        - arm

test_rpi:
    image: resin/raspberrypi2-python:3.5.1
    stage: test
    script:
        - pip3 install -r test-requirements.txt
        - python3 setup.py test
    tags:
        - rpi
        - docker


#####################
# Build Sphinx Docs #
#####################
# use docker image with latex preinstalled

pages:
    image: python
    stage: pages
    script:
        - pip install -r test-requirements.txt
        - python setup.py test
        - python setup.py docs
        - mv htmlcov public/
        - mv docs/_build/html/* public/
    tags:
        - docker
        - x86
    artifacts:
        paths:
        - public
    only:
        - master

###########
# Package #
###########

package:
    image: python
    stage: package
    script:
        - python setup.py sdist bdist_wheel
    artifacts:
        name: "${CI_PROJECT_NAME}_${CI_PIPELINE_ID}"
        paths:
            - dist/
    tags:
        - docker
    only:
        - master
