stages:
    - test
    - pages
    - package


before_script:

    # Kivy / Cython requirements
    - echo "deb http://www.deb-multimedia.org jessie main non-free" >> /etc/apt/sources.list
    - echo "deb-src http://www.deb-multimedia.org jessie main non-free" >> /etc/apt/sources.list
    - apt-get --yes update && apt-get --yes install git build-essential
    - apt-get --yes install ffmpeg libsdl2-dev libsdl2-image-dev
    - apt-get --yes install libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev
    - apt-get --yes install libswscale-dev libavformat-dev libavcodec-dev
    - apt-get --yes install zlib1g-dev
        
    # Install items in requirements.txt in order from top to bottom
    # This is required because the Cython package must be installed
    # before Kivy and pip provides no way to do this.
    - cat requirements.txt | xargs -n 1 -L 1 pip install
    - pip install -U setuptools

########
# Test #
########

test:
    image: python
    stage: test
    script:
        - pip install -r test-requirements.txt
        - python setup.py test
    tags:
        - docker

#####################
# Build Sphinx Docs #
#####################
# use docker image with latex preinstalled

pages:
    image: python
    stage: pages
    script:
        - pip install -r test-requirements.txt
        - python setup.py test
        - python setup.py docs
        - mv htmlcov public/
        - mv docs/_build/html/* public/
    tags:
        - docker
    artifacts:
        paths:
        - public
    only:
        - master

###########
# Package #
###########

package:
    image: python
    stage: package
    script:
        - python setup.py sdist bdist_wheel
    artifacts:
        name: "${CI_PROJECT_NAME}_${CI_PIPELINE_ID}"
        paths:
            - dist/
    tags:
        - docker
    only:
        - master
